model_list:
  - model_name: local-judge
    litellm_params:
      model: openai/ibm-granite/granite-4.0-h-tiny
      api_base: http://cmod-llama:8080/v1
      api_key: dummy

  - model_name: local-thinking
    litellm_params:
      model: openai/LiquidAI/LFM2.5-2.6B
      api_base: http://cmod-llama-thinking:8080/v1
      api_key: dummy

litellm_settings:
  drop_params: true
  callbacks: ["otel"]
  otel: true

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY